---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mydb
  template:
    metadata:
      name: postgres-pod
      labels:
        type: mydb
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
...