---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    type: result-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: result-app
      labels:
        type: result-app
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
...