---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    type: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      name: voting-app
      labels:
        type: voting-app
    spec:
      containers:
        - name: myvoting-app
          image: dockersamples/examplevotingapp_vote
...