---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    type: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-app
      labels:
        type: worker-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
...